# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - junglevscode

on:
  push:
    branches:
      - release/v4.8.2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/alan4103/code-server.git/
        username: ${{ secrets.AzureAppService_ContainerUsername_7879200ca58444948e2bb13cc85d5617 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31f3041b90ac4bf0b28783ce4134a780 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/alan4103/code-server.git/${{ secrets.AzureAppService_ContainerUsername_7879200ca58444948e2bb13cc85d5617 }}/coder/code-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'junglevscode'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc2c16a5123549bbbf73a530916a6eaa }}
        images: 'github.com/alan4103/code-server.git/${{ secrets.AzureAppService_ContainerUsername_7879200ca58444948e2bb13cc85d5617 }}/coder/code-server:${{ github.sha }}'